[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++17

lib_deps = 
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
	adafruit/Adafruit GFX Library@^1.11.11
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.8
	bblanchon/ArduinoJson@^7.0.4
